name: Random Workflow
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context
              run: |
                echo "Yutian Qin Testing..."
                echo "${{ toJson(github) }}"